config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'couples#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :couples, only: [:new, :create, :index, :show, :destroy] do
    resources :bookings, only: [:create, :update]
  end

  get '/dashboard', to: 'users#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :couple
  STATUS = ['en attente', 'acceptée', 'rejetée']
  validates :end_date, date: { after: :start_date }
end

app/models/couple.rb
class Couple < ApplicationRecord
  belongs_to :user
  has_many :bookings
  mount_uploader :photo, PhotoUploader
  validates :name, :address, :description, :price, presence: true
  validates :price, numericality: { only_integer: true }
  validates :user, uniqueness: true
  validates :nickname, uniqueness: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def average
    if self.bookings.first.present?
      sum = 0
      rated_bookings = self.bookings.where.not(review_rating: nil)
      if rated_bookings.first.present?
        rated_bookings.each do |rated_booking|
          sum += rated_booking.review_rating
        end
        avg_float = sum.fdiv(rated_bookings.count)
        return (avg_float * 2).round / 2.0
      else
        return nil
      end
    else
      return nil
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :couple
  has_many :bookings
  mount_uploader :photo, PhotoUploader

  def notifications
    if self.couple
      pending_bookings = self.couple.bookings.where("status = ?", "en attente")
      return pending_bookings.length
    else
      return 0
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname, :dashboard])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @couple = Couple.find(params[:couple_id])
    @booking.couple = @couple
    isbookable = @couple.bookings.all? do |booking|
      (@booking.end_date < booking.start_date) || (booking.end_date < @booking.start_date)
    end
    if isbookable
      @booking.save!
      redirect_to dashboard_path
    else
      @error = true
      @old_bookings = @couple.bookings.where("end_date <= ?", Date.today)
      @reviewed_old_bookings = @old_bookings.where.not(review_content: nil)
      render "couples/show"
    end
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def show
    @booking = Booking.new(booking_params)
    @booking.user = @user
    @booking.couple = @couple
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :start_date, :end_date, :review_content, :review_rating, :status)
  end
end

app/controllers/couples_controller.rb
class CouplesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      sql_query = "name ILIKE :query OR best_quality ILIKE :query"
      @couples = Couple.where(sql_query, query: "%#{params[:query]}%")
    else
      @couples = Couple.geocoded
    end
    @markers = @couples.map do |couple|
      {
        lat: couple.latitude,
        lng: couple.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { couple: couple })
      }
    end
  end

  def show
    @couple = Couple.find(params[:id])
    @booking = Booking.new
    @old_bookings = @couple.bookings.where("end_date <= ?", Date.today)
    @reviewed_old_bookings = @old_bookings.where.not(review_content: nil)
    @markers =
      {
        lat: @couple.latitude,
        lng: @couple.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { couple: @couple })
      }
  end


  def new
    @couple = Couple.new
  end

  def create
    @couple = Couple.new(couple_params)
    @couple.user = current_user
    if @couple.save
      redirect_to couple_path(@couple)
    else
      render :new
    end
  end

  private

  def couple_params
    params.require(:couple).permit(:name, :nickname, :description, :skills, :best_quality, :worst_default, :address, :price, :photo, :user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @upcoming_bookings = current_user.bookings.where("start_date >= ?", Date.today)
    @old_bookings = current_user.bookings.where("end_date <= ?", Date.today)
    @old_bookings_to_review = @old_bookings.where(review_content: nil)
    @reviewed_old_bookings = @old_bookings.where.not(review_content: nil)

    if current_user.couple.nil?
      @bookings_to_validate = ""
    else
      @bookings_to_validate = current_user.couple.bookings.where("status = ?", "en attente")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/couples/_average_stars.html.erb
<% if !couple.average.nil? %>
    <% couple.average.to_i.times do %>
      <i class="fas fa-star"></i>
    <% end %>

    <% if couple.average == (couple.average.to_i + 0.5) %>
      <i class="fas fa-star-half-alt"></i>
    <% end %>

    <% if couple.average != (couple.average.to_i + 0.5) %>
      <% (5 - couple.average.to_i).times do %>
        <i class="far fa-star"></i>
      <% end %>
    <% else %>
      <% (4 - couple.average.to_i).times do %>
        <i class="far fa-star"></i>
      <% end %>
    <% end %>
<% end %>

app/views/couples/_form.html.erb
<div class="container" style= "text-align: center">
  <div class="booking-form" style="width: 400px; margin: 0 auto;">
    <%= simple_form_for [@couple, @booking], wrapper: :inline_form,
  html: { class: "form-inline" },
  wrapper_mappings: {
    boolean: :inline_boolean
  } do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker start_date"}, label: "Début", placeholder: "Date début"%>
      <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker end_date", data: {price: @couple.price}}, label: "Fin", placeholder: "Date fin" %>
  </div>
  <br>
  <%= f.button :submit, "Réserver", class: "button-default turquoise big " %>
  <div class="booking_price"></div>
  <% end %>
</div>

app/views/couples/_info_window.html.erb
<h2><%= couple.name %></h2>
<p><%= couple.address %></p>
<p><%= couple.best_quality %></p>

app/views/couples/copy_show.html.erb
copy_show.html.erb

app/views/couples/index.html.erb
<div class="landing-cover">
  <div class="text-centered">

    <h2 class= "main-title">Trouvez des parents à louer pour  <span class="typed"></span> </h2>

   <button type="button" class="button-default turquoise welcome-button" >
    <a data-scroll href="#scroll-to-all-parents">Voir les parents à louer</a>
   </button>
  </div>
</div>

<div class="row search-center" id="scroll-to-all-parents">
  <%= form_tag couples_path(anchor: "scroll-to-all-parents"), method: :get, class: "form-inline my-2 my-lg-0 search-flex search-wide" do %>
    <%= text_field_tag :query, params[:query], class: "form-control mr-sm-2", id: "search-home", placeholder: "Trouver un couple" %>
    <%= submit_tag "Lancer la recherche", class: "button-default vert my-2 my-sm-0", id: "button-search" %>
  <% end %>
</div>

<div  class="index-container">

  <div class="half-container col-6">

    <div class="row">
      <% @couples.each do |couple| %>
        <div class="col-6">
          <div class="card">

            <div class="card-photo-container">
              <%= cl_image_tag couple.photo, class: 'card-photo', height: 300, width: 400, crop: :fill %>
              <div class="middle">
                <span class="button-default turquoise"><%= link_to 'En savoir +', couple_path(couple) %></span>
              </div>
            </div>

            <div class="card-info">

              <div class="card-info-content">
                <div class="double-info">
                  <div class="box-left">
                    <h4 class="strong">Les <%= couple.name %></h4>
                  </div>
                  <div class="box-right">
                    <p class="lighter">("<%= couple.nickname %>"")</p>
                  </div>
                </div>
                <div class="card-trip-infos justify-content-center align-items-center">
                  <p class="description-couple">"<%= couple.description %>"</p>
                </div>
              </div>

              <div class="card-info-footer">
                <div class="double-info">
                  <div class="box-left">
                    <%= cl_image_tag couple.user.photo, crop: :fill, height: 40, gravity: 'face', class: "card-user-photo avatar-bordered" %>
                    <h2><%= couple.price %> €</h2>
                  </div>
                  <div class="rating float-right">
                    <span><%= render partial: "couples/average_stars", locals: { couple: couple } %></span>
                  </div>
                  <div class="box-right">
                    <span class="bookings-count light-blue small"><%= couple.bookings.count %></span>
                  </div>

                </div>
              </div>

            </div>

          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col-6" id="map" style="width: 100%; height: 100vh; position: sticky; top: 0; margin-left: 30px; margin-bottom: 30px; margin-right: 30px;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/couples/new.html.erb
<div class="container">
  <h1 class="my-5">Je mets mes parents en location</h2>

  <%= simple_form_for (@couple) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="form-inputs">
      <%= f.input :name, label: 'Leur nom' %>
    </div>
    <div class="form-inputs">
      <%= f.input :nickname, label: 'Leur surnom' %>
    </div>
    <div class="form-inputs">
      <%= f.input :description, label: 'Une petite description' %>
    </div>
    <div class="form-inputs">
      <%= f.input :skills, label: 'Leurs compétences' %>
    </div>
    <div class="form-inputs">
      <%= f.input :best_quality, label: 'Leur plus grande qualité' %>
    </div>
    <div class="form-inputs">
      <%= f.input :worst_default, label: 'Leur pire défaut' %>
    </div>
    <div class="form-inputs">
      <%= f.input :address, label: 'Leur adresse' %>
    </div>
    <div class="form-inputs">
      <%= f.input :price, label: 'Leur tarif' %>
    </div>
    <div class="form-inputs">
      <%= f.input :photo, label: 'Une petite photo' %>
      <%= f.input :photo_cache, as: :hidden %>
    </div>
    <div class="form-actions">
      <%= f.submit "Mes ieuv sur les internets", class: "btn btn-primary" %>
    </div>
  <% end %>

</div>

app/views/couples/show.html.erb
<div class="container mt-5">
  <div class="show-container">
    <%= cl_image_tag @couple.photo, width: 600, class: "show-image" %>
      <div class="show-information">
         <div class="show-name">
           <h1>Les <%= @couple.name %></h1>
           <h3 class="show-price"><%= @couple.price%> €</i></h3>
           <h4><%= @couple.address %></h4>
        </div>
          <div class="show-details">
             <p> <strong></strong> "<%= @couple.description %> "</p> <br>
             <p id="show-star"> <span ><%= render partial: "couples/average_stars", locals: { couple: @couple } %></span> </p>  <br>
             <div class="image-emoji">
              <p><%= cl_image_tag('thumb-down_ffnoaz',width: 30, height: 30) %>   <%= @couple.worst_default %> </p>
              <p> <%= cl_image_tag('thumbs-up_vigkhn',width: 30, height: 30) %>   <%= @couple.best_quality %> </p>
             </div>
          </div>

          <% if @error %>
            <p style="color: red"> Ces parents sont déjà réservés sur cette date ! </p>
          <% end %>

          <% if @couple.user == current_user %>
            <p>Vous n'allez quand même pas louer vos propres parents...</p>
          <% else %>
            <br>
            <div class="">
              <div class="">

                <div  class= "booking_details"><p class="booking_price"></p><p class="booking_reservation"></p></div>

                <%= render 'couples/form', booking: Booking.new %>

                  <br>
              <div class="card-review-rating">

                <% @reviewed_old_bookings.each do |booking| %>

                <div class="card-product2">
                  <%= cl_image_tag booking.user.photo, class: 'card-photo', height: 40, width: 40 %>
                  <div class="card-product-infos2">
                    <p>Avis laissé le : <%= booking.end_date %></p>
                    <h2><% booking.review_rating.times do %>
                         <i class="fas fa-star"></i>
                       <% end %>
                       <% (5 - booking.review_rating).times do %>
                         <i class="far fa-star"></i>
                      <% end %></h2>
                    <p> "<%= booking.review_content %> "</p>
                  </div>
                </div>

                <% end %>
              </div>
            <% end %>
          </div>
        </div>
    </div>
  </div>

app/views/dashboards/show.html.erb
<h1>My dashboard</h1>

<%= cl_image_tag(current_user.photo, :transformation=>[
  {:width=>400, :height=>400, :gravity=>"face", :radius=>"max", :crop=>"crop"},
  {:width=>40, :crop=>"scale"}
  ]) %>

<p><%= current_user.fullname %></p>

<%= link_to 'Edit profile',  edit_user_registration_path %>

<% if current_user.photo.file.nil? %>
  <p>Ajoutez votre trombine :</p>
<% else %>
  <%= cl_image_tag current_user.photo %>
<% end %>

<h2>My parents</h2>

<%= cl_image_tag(current_user.couple.photo, :transformation=>[
  {:width=>400, :height=>400, :gravity=>"face", :radius=>"max", :crop=>"crop"},
  {:width=>80, :crop=>"scale"}
  ]) %>

<p><%= current_user.couple.name %></p>

<% current_user.couple.bookings.each do |booking| %>
  <p><%= booking.status %></p>
<% end %>

<h2>My reservations</h2>

<% current_user.bookings.each do |booking| %>
  <p><%= booking.start_date %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>PARHUNT</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
      <%= stylesheet_pack_tag 'application' %> <!-- NEW! -->
       <%= javascript_pack_tag 'application' %>
       <%= favicon_link_tag asset_path('logo.png') %>
   <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->

  </head>

  <body>

    <%= render 'shared/navbar' %>

    <div class=" min-height">
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>






    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/louwelgryn/parhunt" target="_blank"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/lewagonparis/?hl=fr" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://fr-fr.facebook.com/lewagon/" target="_blank"><i class="fab fa-facebook"></i></a>
    <a href="https://www.linkedin.com/school/le-wagon/" target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    With <i class="fas fa-heart"></i> from Parhunt
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-lewagon navbar-lewagon-white">
  <p><%= link_to "PARHUNT", couples_path(anchor: "scroll-to-all-parents" ) %> <i class="fas fa-female"></i><i class="fas fa-male"></i></p>
  <div id="navbar-btns-avatar">
    <button type="button" class="button-default turquoise" >
      <span data-scroll > <%=link_to 'Voir les parents à louer',couples_path(anchor: "scroll-to-all-parents")   %> </span>
    </button>
    <% if current_user && current_user.couple.nil? %>
      <button type="button" class="button-default turquoise button-navbar"><%= link_to "Louez vos parents", new_couple_path %></button>
    <% end %>
    <% if current_user.nil? %>
      <button type="button" class="button-default rouge button-navbar"><%= link_to "Se connecter", new_user_session_path %></button>
    <% else  %>
      <button type="button" class="button-default turquoise-light button-navbar"> <%= link_to('Se déconnecter', destroy_user_session_path, method: :delete) %></button>
      <%= link_to dashboard_path do %>
        <div>
          <div>
             <%= cl_image_tag current_user.photo,crop: :fill, width: 1000, gravity: :auto, radius: "max", aspect_ratio: "1:1", class: "avatar" %>
          </div>
          <% if current_user.notifications > 0 %>
            <div id="navbar-notif-badge">
              <%= current_user.notifications %>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/_circles.html.erb
<div display_container>
  <ul class="display-container">

    <% if @current_user.couple.bookings.nil? && @current_user.bookings.nil? %>

    <% else %>

      <li class="note-display" data-note=<%= @current_user.couple.bookings.length + @current_user.bookings.length %>>
        <div class="circle">
          <svg width="84" height="84" class="circle__svg">
            <circle cx="41" cy="41" r="38" class="circle__progress circle__progress--path"></circle>
            <circle cx="41" cy="41" r="38" class="circle__progress circle__progress--fill"></circle>
          </svg>

          <div class="percent">
            <span class="percent__int"><%= @current_user.couple.bookings.length + @current_user.bookings.length %></span>
            <span class="percent__dec"></span>
          </div>
        </div>

        <span class="label">RESERVATIONS EFFECTUEES</span>
      </li>

    <% end %>

    <li class="note-display" data-note=<%= @bookings_to_validate.length %>>
      <div class="circle">
        <svg width="84" height="84" class="circle__svg">
          <circle cx="41" cy="41" r="38" class="circle__progress circle__progress--path"></circle>
          <circle cx="41" cy="41" r="38" class="circle__progress circle__progress--fill"></circle>
        </svg>

        <div class="percent">
          <span class="percent__int">
            <%= @bookings_to_validate.length %>
          </span>
        </div>
      </div>

      <span class="label">RESERVATIONS A VALIDER</span>
    </li>

    <li class="note-display" data-note=<%= @old_bookings_to_review.length %>>
      <div class="circle">
        <svg width="84" height="84" class="circle__svg">
          <circle cx="41" cy="41" r="38" class="circle__progress circle__progress--path"></circle>
          <circle cx="41" cy="41" r="38" class="circle__progress circle__progress--fill"></circle>
        </svg>

        <div class="percent">
          <span class="percent__int">
            <%= @old_bookings_to_review.length %>
          </span>
        </div>
      </div>

      <span class="label">RESERVATIONS A NOTER</span>
    </li>
  </ul>
</div>

app/views/users/_evaluation_form.html.erb
<% @old_bookings_to_review.each do |old_booking_to_review| %>
  <p>Vous avez réservé les <span class="rouge"><%= old_booking_to_review.couple.name %></span> du <%= old_booking_to_review.start_date %> au <%= old_booking_to_review.end_date %></p>
  <%= simple_form_for [old_booking_to_review.couple, old_booking_to_review] do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="form-inputs">
      <p>Laissez leur un commentaire :</p>
      <%= f.input :review_content, label: false %>
    </div>
    <div class="form-inputs DB-ratings">
      <p>Notez-les : <%= f.collection_radio_buttons :review_rating, [[0, '0'],[1, '1'] ,[2, '2'],[3, '3'],[4, '4'],[5, '5']], :first, :last %></p>
    </div>
    <div class="form-inputs">
      <%= f.submit %>
    </div>
  <% end %>
<% end %>

app/views/users/_mes_parents.html.erb
<div class="parents">

  <% if current_user.couple.nil? %>
    <p class="button-default rouge"> <%= link_to 'Mettre mes parents à louer', new_couple_path %></p>
  <% else %>
    <div class="dashboard-parents-card">
      <div class="dashboard-parents-avatar" style="background-image: url('<%= cl_image_path current_user.couple.photo, gravity: :face; %>'); background-repeat:no-repeat;"></div>
      <div class="dashboard-parents-info">
        <h2>Les <%= current_user.couple.name %></h2>
        <p class="button-default light-blue"><%= link_to 'Voir leur page', couple_path(current_user.couple) %></p>
      </div>
    </div>

    <% if current_user.couple.bookings.any?  %>

      <h2>Leurs réservations :</h2>

      <% current_user.couple.bookings.each do |booking| %>
        <div class="card-product">
          <%= cl_image_tag(booking.user.photo) %>
          <div class="card-product-infos">
            <span class="rouge"><%= booking.user.fullname %></span>
            <p>Du <%= booking.start_date %> au <%= booking.end_date %></p>
            <%= simple_form_for [current_user.couple, booking] do |f| %>
              <%= f.error_notification %>
              <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
              <div class="form-inputs">
                <%= f.input :status, :collection => Booking::STATUS, label: "Statut :" %>
              </div>
              <div class="form-inputs">
                <%= f.submit %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/_mes_reservations.html.erb
<div class="parents">

  <div class="booking-card">
    <h3>Réservations à venir</h3>
    <% @upcoming_bookings.each do |upcoming_booking| %>
      <li>
        <div class="card-product">
          <%= cl_image_tag(upcoming_booking.couple.photo) %>
          <div class="card-product-infos">
              <span class="rouge"><%= upcoming_booking.couple.name %></span>
              <p>Du <%= upcoming_booking.start_date %> au <%= upcoming_booking.end_date %></p>
              <p><strong>Cette réservation est <%= upcoming_booking.status %></strong></p>
          </div>
        </div>
      </li>
    <% end %>
  </div>

  <hr>

  <div class="booking-card">
    <h3>Réservations à évaluer</h3>
    <%= render 'evaluation_form' %>
  </div>

  <hr>

  <div class="booking-card">
    <h3>Réservations passées</h3>
    <% @reviewed_old_bookings.each do |reviewed_old_booking| %>
      <p>Vous avez réservé les <span class="rouge"><%= reviewed_old_booking.couple.name %></span> du <%= reviewed_old_booking.start_date %> au <%= reviewed_old_booking.end_date %>.
      <p>Votre évaluation : "<%= reviewed_old_booking.review_content %>". Vous leur avez donné la note de <strong><%= reviewed_old_booking.review_rating %></strong>.</p>
    <% end %>
  </div>

</div>

app/views/users/_mesresa.html.erb
<div class="parents">
  <h2><strong>MES RESERVATIONS</strong></h2>

    <div class="booking-card">
      <h3>Réservations à venir</h3>
        <% @upcoming_bookings.each do |upcoming_booking| %>
        <li>

            <hr>
            <div class="card-product">
              <%= cl_image_tag(upcoming_booking.couple.photo) %>
                <div class="card-product-infos">
                  <span class="rouge"><%= upcoming_booking.couple.name %></span>
                    <p> Du <%= upcoming_booking.start_date %> au <%= upcoming_booking.end_date %>
                    </p>
                    <p><strong>Cette réservation est <%= upcoming_booking.status %></strong></p>

            </div>
            </li>
        <% end %>


    <div class="booking-card">
      <h3>Réservations à évaluer</h3>
      <%= render 'evaluation_form' %>
    </div>

    <div class="booking-card">
      <h3>Réservations passées</h3>

      <% @reviewed_old_bookings.each do |reviewed_old_booking| %>

        <p>Vous avez réservé les <span class="rouge"><%= reviewed_old_booking.couple.name %></span> du <%= reviewed_old_booking.start_date %> au <%= reviewed_old_booking.end_date %>.
        <p>Votre évaluation : "<%= reviewed_old_booking.review_content %>". Vous leur avez donné la note de <strong><%= reviewed_old_booking.review_rating %></strong>.</p>

      <% end %>
    </div>
  </div>
</div>

app/views/users/dashboard.html.erb
<div class="dashboard-cover">
  <div class="dashboard-cover-child">
    <h1 class="text-center main-title-dashboard">MON DASHBOARD</h1>
      <p class="text-white"><%= current_user.fullname %></p>
    <div d-flex>
      <%= link_to 'Editer le profil', edit_user_registration_path, class: "button-default white opacity-08" %>
    </div>
    <br>
    <%= render 'circles' %>
  </div>
</div>



<div class="mx-auto">
  <ul class="nav margin-left" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active tab-label" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">MES PARENTS</a>
    </li>
    <li class="nav-item">
      <a class="nav-link tab-label" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">MES RESERVATIONS</a>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active tab-content" id="home" role="tabpanel" aria-labelledby="home-tab">
      <%= render 'mes_parents' %>
    </div>
    <div class="tab-pane fade tab-content" id="profile" role="tabpanel" aria-labelledby="profile-tab">
      <%= render 'mes_reservations' %>
    </div>
  </div>
</div>